/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student;

import Ujaalo.AddEvents;
import Ujaalo.Events;
import Ujaalo.Login;
import static Ujaalo.Events.BookDate;
import static Ujaalo.Events.Category;
import static Ujaalo.Events.EventDate;
import static Ujaalo.Events.EventID;
import static Ujaalo.Events.EventName;
import static Ujaalo.Events.NoSeats;
import static Ujaalo.Events.Rate;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class BillGeneration extends javax.swing.JFrame {

    /**
     * Creates new form BillGeneration
     */
    public BillGeneration() {
        initComponents();
        InvoiceGeneration();
    }

    
    public void InvoiceGeneration(){
        
        
        String EventID = Events.EventID.getText();
        
        String EventName=Events.EventName.getText();
        
         String EventCat=Events.Category.getText();
         
          String EventDate=Events.EventDate.getText();
          
          String value1=Events.NoSeats.getSelectedItem().toString();
          
          String BookDate =Events.BookDate.getText();
          
          String  Rate = Events.Rate.getText();
        
           int Seats = Integer.parseInt(value1);
           
           int rate=Integer.parseInt(Rate);
           
           int Amount = Seats * rate;
           
           String TotalAmount = new Integer(Amount).toString();
            String UnID=Login.txt_unID.getText();
        
      area.setText("\n");
      
      area.setText(area.getText()+"*************             Ujaalo Student Kiosk Invoice Generation               ************\n\n");
      Date d = new Date();
      
      SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss a");
        
        area.setText(area.getText()+"                                                                        Generated Date  :-   "+s.format(d)+"\n\n");
        
        area.setText(area.getText()+"                          UniversityID :-   " +UnID+"\n");
        area.setText(area.getText()+"                          EventID :-        " +EventID+"\n");
        area.setText(area.getText()+"                          EventName :-      " +EventName+"\n");
        area.setText(area.getText()+"                          Category :-       " +EventCat+"\n");
        area.setText(area.getText()+"                          EventDate :-      "+EventDate +"\n");
        area.setText(area.getText()+"                          No.of Seats :-    " +value1+"\n");
        area.setText(area.getText()+"                          Book Date :-      " +BookDate+"\n");
        area.setText(area.getText()+"                          Rate :-           " +Rate +"\n\n");
        
        area.setText(area.getText()+"                                                        Total Amount :- " +TotalAmount +"\n");
        
                
        //area.setText(area.getText()+"                                                                                       ");
       
      
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterLoginMain = new javax.swing.JPanel();
        RegisterName = new javax.swing.JLabel();
        BackPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        RegisterLoginMain.setBackground(new java.awt.Color(255, 255, 255));
        RegisterLoginMain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        RegisterLoginMain.setPreferredSize(new java.awt.Dimension(700, 509));

        RegisterName.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        RegisterName.setForeground(new java.awt.Color(214, 48, 49));
        RegisterName.setText("Invoice Generation");

        BackPanel.setBackground(new java.awt.Color(214, 48, 49));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BackPanelLayout = new javax.swing.GroupLayout(BackPanel);
        BackPanel.setLayout(BackPanelLayout);
        BackPanelLayout.setHorizontalGroup(
            BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackPanelLayout.setVerticalGroup(
            BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        addBtn.setBackground(new java.awt.Color(214, 48, 49));
        addBtn.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Print Invoice");
        addBtn.setBorder(null);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        area.setEditable(false);
        area.setColumns(20);
        area.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        javax.swing.GroupLayout RegisterLoginMainLayout = new javax.swing.GroupLayout(RegisterLoginMain);
        RegisterLoginMain.setLayout(RegisterLoginMainLayout);
        RegisterLoginMainLayout.setHorizontalGroup(
            RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLoginMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegisterName)
                .addGap(164, 164, 164)
                .addComponent(BackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 61, Short.MAX_VALUE))
        );
        RegisterLoginMainLayout.setVerticalGroup(
            RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RegisterName)
                    .addComponent(BackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterLoginMain, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterLoginMain, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed

        try {
            area.print();
        } catch (PrinterException ex) {
            Logger.getLogger(BillGeneration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillGeneration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillGeneration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillGeneration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillGeneration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillGeneration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackPanel;
    private javax.swing.JPanel RegisterLoginMain;
    private javax.swing.JLabel RegisterName;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextArea area;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
