/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student;

import Ujaalo.Login;
import Ujaalo.OracleDatabase;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author User
 */
public class StudentBookings extends javax.swing.JFrame {

    /**
     * Creates new form StudentBookings
     */
    
    
     Connection conn=null;
    OraclePreparedStatement pst=null;
    OracleResultSet rs = null;
    
    
    
    public StudentBookings() {
        initComponents();
        EventList();
    }
    
    
    
    public void EventList(){
    
    DefaultTableModel table = new DefaultTableModel();
    
   // TableColumnModel cmodel = table.getColumnModel(); 
     //   TextAreaRenderer textAreaRenderer = new TextAreaRenderer(); 
    
   //TextAreaRenderer textAreaRenderer = new TextAreaRenderer();
   
    
    table.addColumn("Book ID");
    //table.addColumn("EventID");
    table.addColumn("Event Name");
    table.addColumn("Category");
    table.addColumn("Event Date");
    table.addColumn("No of Booked Seats");
    table.addColumn("Booked Date");
    
    conn = OracleDatabase.ConnectDb();
    try
    {
        //conn = OracleDatabase.ConnectDb();
        String sql = "SELECT BookID,EventsName,Category,EventDate,NoOfSeats,BookedDate FROM Booking WHERE UniversityID=?";
        
        pst = (OraclePreparedStatement) conn.prepareStatement(sql);
        pst.setString(1,Login.txt_unID.getText());
        
        rs =(OracleResultSet) pst.executeQuery();
        
        //ResultSet R = S.executeQuery(sql);
        
        while(rs.next()){
            table.addRow(new Object[]{
                rs.getString(1),
                
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6),
                //rs.getString(7),
                //rs.getString(6)
            });
        }
        BookingList.setModel(table);
        BookingList.setShowHorizontalLines(true); 
        BookingList.setGridColor(Color.white);
        // TableColumnModel cmodel = EventsList.getColumnModel(); 
         
    
        //cmodel.getColumn(1).setCellRenderer(textAreaRenderer);
        
        //TextAreaRenderer textAreaRenderer = new TextAreaRenderer();
        //cmodel.getColumn(1).setCellRenderer(textAreaRenderer); 
        
        
        
        
        
    }catch(Exception e){
        
    }
    
    
   

    
   
}
    
    
    
    
    public void CancelBookings(){
        
        conn = OracleDatabase.ConnectDb();
        
        DefaultTableModel model = (DefaultTableModel)BookingList.getModel();

        // get the selected row index
        int selectedRowIndex = BookingList.getSelectedRow();

        // set the selected row data into jtextfields
        String BID =model.getValueAt(selectedRowIndex, 0).toString();
     
        try{
            String deleteOracle = "DELETE FROM Booking WHERE UniversityID=? AND BookID=?";
                    
          //UPDATE Student SET Password=? WHERE UniversityID=?"
            
            pst = (OraclePreparedStatement) conn.prepareStatement(deleteOracle);
            
             pst.setString(1,Login.txt_unID.getText());
             pst.setString(2,BID);

            rs =(OracleResultSet) pst.executeQuery();

            if (rs.next())
            {
                JOptionPane.showMessageDialog(null,"Delete of selected Booking Successful.Note that you will loss the Bpooking Data and its whole details.");

                
            }

            else
            {
                JOptionPane.showMessageDialog(null,"Delete of Booking Unsuccessful");
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
        
        
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        EventsList = new javax.swing.JTable();
        RegisterLoginMain = new javax.swing.JPanel();
        RegisterName = new javax.swing.JLabel();
        BackPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BookingList = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        EventsList.setAutoCreateRowSorter(true);
        EventsList.setBackground(new java.awt.Color(99, 110, 114));
        EventsList.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 51, 51)));
        EventsList.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        EventsList.setForeground(new java.awt.Color(255, 255, 255));
        EventsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Event ID", "Event Name", "Category", "Description", "Event Date", "Total Seats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EventsList.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        EventsList.setRowHeight(150);
        EventsList.setRowMargin(2);
        EventsList.setRowSorter(null);
        EventsList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        EventsList.setUpdateSelectionOnSort(false);
        EventsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EventsListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(EventsList);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(705, 626));
        setUndecorated(true);

        RegisterLoginMain.setBackground(new java.awt.Color(255, 255, 255));
        RegisterLoginMain.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));
        RegisterLoginMain.setPreferredSize(new java.awt.Dimension(700, 450));

        RegisterName.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        RegisterName.setForeground(new java.awt.Color(214, 48, 49));
        RegisterName.setText("My Bookings");

        BackPanel.setBackground(new java.awt.Color(214, 48, 49));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BackPanelLayout = new javax.swing.GroupLayout(BackPanel);
        BackPanel.setLayout(BackPanelLayout);
        BackPanelLayout.setHorizontalGroup(
            BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackPanelLayout.setVerticalGroup(
            BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        BookingList.setBackground(new java.awt.Color(99, 110, 114));
        BookingList.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 51, 51)));
        BookingList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        BookingList.setRowHeight(150);
        BookingList.setRowMargin(2);
        BookingList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(BookingList);

        jButton1.setBackground(new java.awt.Color(214, 48, 49));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancel Bookings");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterLoginMainLayout = new javax.swing.GroupLayout(RegisterLoginMain);
        RegisterLoginMain.setLayout(RegisterLoginMainLayout);
        RegisterLoginMainLayout.setHorizontalGroup(
            RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLoginMainLayout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLoginMainLayout.createSequentialGroup()
                        .addComponent(RegisterName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(259, 259, 259)
                        .addComponent(BackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLoginMainLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(290, 290, 290))))
        );
        RegisterLoginMainLayout.setVerticalGroup(
            RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterName, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterLoginMain, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterLoginMain, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void EventsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EventsListMouseClicked
        
    }//GEN-LAST:event_EventsListMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       
        CancelBookings();
        
        EventList();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BookingListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingListMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)BookingList.getModel();

        // get the selected row index
        int selectedRowIndex = BookingList.getSelectedRow();

        // set the selected row data into jtextfields
        String BID =model.getValueAt(selectedRowIndex, 0).toString();
        
    }//GEN-LAST:event_BookingListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentBookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackPanel;
    private javax.swing.JTable BookingList;
    private javax.swing.JTable EventsList;
    private javax.swing.JPanel RegisterLoginMain;
    private javax.swing.JLabel RegisterName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
