/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ujaalo;

import Student.StudentInfo;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.RowFilter;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import oracle.jdbc.rowset.OracleCachedRowSet;



/**
 
 * @author User
 */
public class AdminPanel extends javax.swing.JFrame {

    
    
    /**
     * Creates new form AdminPanel
     */
    
    
    Connection conn=null;
    OraclePreparedStatement pst=null;
    OracleResultSet rs = null;
    
    public AdminPanel() {
        initComponents();
        
         ShowDate(); //Method For Showing Date in Jlabel named lbl_Date
        
        ShowTime(); //Method For Showing Time in JLabel named lbl_Time
        
       EventList();//Method for showing all the events in in main dashboard in java
       
       TotalBook(); //Method to count total number of events and show in Total Events
       
       TotalEvent();  //Method to count total number of events and show in Total Events
    }
    
    
    
    
    public void EventList(){
    
    DefaultTableModel table = new DefaultTableModel();
    
       
   
    
    table.addColumn("Event ID");
    table.addColumn("Event Name");
    table.addColumn("Category");
    table.addColumn("Description");
    table.addColumn("Venue");
    table.addColumn("Event Date");
    table.addColumn("Total Seats");
    
    conn = OracleDatabase.ConnectDb();
    try
    {
        //conn = OracleDatabase.ConnectDb();
        String sql = "SELECT EventID,EventsName,Category,Description,Venue,EventDate,NoOfSeats FROM Events";
        
        pst = (OraclePreparedStatement) conn.prepareStatement(sql);
        
        
        rs =(OracleResultSet) pst.executeQuery();
        
        //ResultSet R = S.executeQuery(sql);
        
        while(rs.next()){
            table.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6),
                rs.getString(7),
                //txtCourse.setText(rs.getString(2));
            });
        }
        EventsList.setModel(table);
        EventsList.setShowHorizontalLines(true); 
        EventsList.setGridColor(Color.white);
        
        
        
        
        
        
    }catch(Exception e){
        
    }
    
   
    }
    
    
    public void TotalEvent(){
        
        int rows = EventsList.getRowCount();
        String TE = new Integer(rows).toString();
        txtTotalEvents.setText(TE);
    }
    
    
    
    
    
    public void TotalBook(){
        
       
         conn = OracleDatabase.ConnectDb();
    try
    {
         OracleCachedRowSet ocrs = new OracleCachedRowSet();      //This is the oracle Cached Row Set which is calculated by Manuall Codes
         
         
        String sql = "SELECT BookID FROM Booking";
        
        pst = (OraclePreparedStatement) conn.prepareStatement(sql);
       
        
        rs =(OracleResultSet) pst.executeQuery();
        ocrs.populate(rs);
        
        ocrs.last();      
        
        int rowcount = ocrs.getRow();

      
        
        
             String totalBook = new Integer(rowcount).toString();
            //tring totalbook= rs.ge
            TotalBook.setText(totalBook);
        if (ocrs != null) 
        ocrs.close();
       
  
        
        
        
    }catch(Exception e){
        
    }
    
    
   

    
     
        
    }
    
    
    
    
    
    
    private void filter(String query)
    
    {
        DefaultTableModel table = new DefaultTableModel();
        TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel>(table);
        EventsList.setRowSorter(tr);
        
        
        tr.setRowFilter(RowFilter.regexFilter(query));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    
     //Method Showing Date
    void ShowDate(){
        
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        lbl_Date.setText(s.format(d));
        
    }
    
    
    void ShowTime(){
        new Timer(0,new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e){
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                lbl_Time.setText(s.format(d));
                   
            }  
        }
              
        ).start();
              
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel1 = new javax.swing.JPanel();
        SideTabPanel1 = new javax.swing.JPanel();
        UniversityLogo1 = new javax.swing.JLabel();
        btn_Dashboard = new javax.swing.JButton();
        btn_ViewBooking = new javax.swing.JButton();
        btn_AddEvents = new javax.swing.JButton();
        btn_AlterEvents = new javax.swing.JButton();
        btn_ViewUserLog = new javax.swing.JButton();
        icon_help1 = new javax.swing.JLabel();
        lbl_help1 = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        IconLogOut = new javax.swing.JLabel();
        dyanmicPanel = new javax.swing.JPanel();
        Date = new javax.swing.JLabel();
        lbl_Date = new javax.swing.JLabel();
        lbl_Time = new javax.swing.JLabel();
        CategoryPanel = new javax.swing.JPanel();
        category = new javax.swing.JPanel();
        lblCategory = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Category = new javax.swing.JComboBox<>();
        TotalEventsPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTotalEvents = new javax.swing.JLabel();
        TotalBookingPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TotalBook = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EventsList = new javax.swing.JTable();
        RefershEvents = new javax.swing.JButton();
        EditUserInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);

        MainPanel1.setBackground(new java.awt.Color(99, 110, 114));
        MainPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        MainPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        MainPanel1.setPreferredSize(new java.awt.Dimension(1372, 768));

        SideTabPanel1.setBackground(new java.awt.Color(237, 28, 36));
        SideTabPanel1.setMaximumSize(new java.awt.Dimension(270, 768));
        SideTabPanel1.setMinimumSize(new java.awt.Dimension(270, 768));

        UniversityLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/uu1.png"))); // NOI18N

        btn_Dashboard.setBackground(new java.awt.Color(237, 28, 36));
        btn_Dashboard.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        btn_Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/club12.png"))); // NOI18N
        btn_Dashboard.setText("      Dashboard      ");
        btn_Dashboard.setBorder(null);
        btn_Dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_DashboardMousePressed(evt);
            }
        });

        btn_ViewBooking.setBackground(new java.awt.Color(237, 28, 36));
        btn_ViewBooking.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_ViewBooking.setForeground(new java.awt.Color(255, 255, 255));
        btn_ViewBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/e-library.png"))); // NOI18N
        btn_ViewBooking.setText("    View Bookings   ");
        btn_ViewBooking.setToolTipText("");
        btn_ViewBooking.setBorder(null);
        btn_ViewBooking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ViewBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ViewBookingActionPerformed(evt);
            }
        });

        btn_AddEvents.setBackground(new java.awt.Color(237, 28, 36));
        btn_AddEvents.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_AddEvents.setForeground(new java.awt.Color(255, 255, 255));
        btn_AddEvents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BREO.png"))); // NOI18N
        btn_AddEvents.setText("      Add Events      ");
        btn_AddEvents.setBorder(null);
        btn_AddEvents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_AddEvents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AddEventsMouseClicked(evt);
            }
        });
        btn_AddEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddEventsActionPerformed(evt);
            }
        });

        btn_AlterEvents.setBackground(new java.awt.Color(237, 28, 36));
        btn_AlterEvents.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_AlterEvents.setForeground(new java.awt.Color(255, 255, 255));
        btn_AlterEvents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Clubs1.png"))); // NOI18N
        btn_AlterEvents.setText("    Alter Events     ");
        btn_AlterEvents.setBorder(null);
        btn_AlterEvents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_AlterEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AlterEventsActionPerformed(evt);
            }
        });

        btn_ViewUserLog.setBackground(new java.awt.Color(237, 28, 36));
        btn_ViewUserLog.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_ViewUserLog.setForeground(new java.awt.Color(255, 255, 255));
        btn_ViewUserLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/changepassword.png"))); // NOI18N
        btn_ViewUserLog.setText("      View User Log ");
        btn_ViewUserLog.setBorder(null);
        btn_ViewUserLog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ViewUserLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ViewUserLogActionPerformed(evt);
            }
        });

        icon_help1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/help.png"))); // NOI18N
        icon_help1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_help1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_help1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_help1.setText("Help");

        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        IconLogOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IconLogOut.setForeground(new java.awt.Color(255, 255, 255));
        IconLogOut.setText("Log Out");
        IconLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconLogOutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SideTabPanel1Layout = new javax.swing.GroupLayout(SideTabPanel1);
        SideTabPanel1.setLayout(SideTabPanel1Layout);
        SideTabPanel1Layout.setHorizontalGroup(
            SideTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_ViewBooking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_AddEvents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_AlterEvents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_ViewUserLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideTabPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(UniversityLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideTabPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblLogout)
                .addGap(18, 18, 18)
                .addComponent(IconLogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_help1)
                .addGap(18, 18, 18)
                .addComponent(lbl_help1)
                .addGap(31, 31, 31))
        );
        SideTabPanel1Layout.setVerticalGroup(
            SideTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideTabPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(UniversityLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btn_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_ViewBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_AddEvents, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_AlterEvents, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_ViewUserLog, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(SideTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideTabPanel1Layout.createSequentialGroup()
                        .addGroup(SideTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SideTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(icon_help1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_help1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblLogout, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideTabPanel1Layout.createSequentialGroup()
                        .addComponent(IconLogOut)
                        .addGap(31, 31, 31))))
        );

        dyanmicPanel.setBackground(new java.awt.Color(99, 110, 114));
        dyanmicPanel.setMaximumSize(new java.awt.Dimension(1090, 768));
        dyanmicPanel.setMinimumSize(new java.awt.Dimension(1090, 768));
        dyanmicPanel.setPreferredSize(new java.awt.Dimension(1096, 768));

        Date.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 255, 255));
        Date.setText("Date :");

        lbl_Date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Date.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Date.setText("Date");

        lbl_Time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Time.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Time.setText("Time");

        CategoryPanel.setBackground(new java.awt.Color(255, 255, 255));
        CategoryPanel.setForeground(new java.awt.Color(255, 102, 102));
        CategoryPanel.setPreferredSize(new java.awt.Dimension(300, 238));

        category.setBackground(new java.awt.Color(237, 28, 36));

        lblCategory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblCategory.setText("Category");

        javax.swing.GroupLayout categoryLayout = new javax.swing.GroupLayout(category);
        category.setLayout(categoryLayout);
        categoryLayout.setHorizontalGroup(
            categoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblCategory)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        categoryLayout.setVerticalGroup(
            categoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/category_icon.png"))); // NOI18N

        Category.setBackground(new java.awt.Color(255, 51, 51));
        Category.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Category.setForeground(new java.awt.Color(255, 255, 255));
        Category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Campus", "Community" }));
        Category.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CategoryItemStateChanged(evt);
            }
        });
        Category.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CategoryKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout CategoryPanelLayout = new javax.swing.GroupLayout(CategoryPanel);
        CategoryPanel.setLayout(CategoryPanelLayout);
        CategoryPanelLayout.setHorizontalGroup(
            CategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(category, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CategoryPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(CategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CategoryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addContainerGap(235, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CategoryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
            .addComponent(Category, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CategoryPanelLayout.setVerticalGroup(
            CategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryPanelLayout.createSequentialGroup()
                .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TotalEventsPanel.setBackground(new java.awt.Color(255, 255, 255));
        TotalEventsPanel.setForeground(new java.awt.Color(153, 0, 51));
        TotalEventsPanel.setPreferredSize(new java.awt.Dimension(253, 238));

        jPanel8.setBackground(new java.awt.Color(153, 153, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(300, 37));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Events");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addpost_1.png"))); // NOI18N

        txtTotalEvents.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        txtTotalEvents.setForeground(new java.awt.Color(51, 51, 255));
        txtTotalEvents.setText("1");
        txtTotalEvents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTotalEventsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TotalEventsPanelLayout = new javax.swing.GroupLayout(TotalEventsPanel);
        TotalEventsPanel.setLayout(TotalEventsPanelLayout);
        TotalEventsPanelLayout.setHorizontalGroup(
            TotalEventsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalEventsPanelLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(TotalEventsPanelLayout.createSequentialGroup()
                .addGroup(TotalEventsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TotalEventsPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TotalEventsPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(txtTotalEvents, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TotalEventsPanelLayout.setVerticalGroup(
            TotalEventsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalEventsPanelLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalEvents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TotalBookingPanel.setBackground(new java.awt.Color(255, 255, 255));
        TotalBookingPanel.setForeground(new java.awt.Color(102, 255, 0));
        TotalBookingPanel.setPreferredSize(new java.awt.Dimension(253, 238));

        jPanel7.setBackground(new java.awt.Color(153, 0, 153));
        jPanel7.setPreferredSize(new java.awt.Dimension(300, 37));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Booking");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_notification.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText(" Booking Notifications");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        TotalBook.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        TotalBook.setForeground(new java.awt.Color(51, 51, 255));
        TotalBook.setText("1");

        javax.swing.GroupLayout TotalBookingPanelLayout = new javax.swing.GroupLayout(TotalBookingPanel);
        TotalBookingPanel.setLayout(TotalBookingPanelLayout);
        TotalBookingPanelLayout.setHorizontalGroup(
            TotalBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalBookingPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(TotalBookingPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TotalBook, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TotalBookingPanelLayout.setVerticalGroup(
            TotalBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalBookingPanelLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TotalBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        EventsList.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 0, 51)));
        EventsList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EventsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        EventsList.setRowHeight(60);
        jScrollPane1.setViewportView(EventsList);

        RefershEvents.setBackground(new java.awt.Color(255, 51, 51));
        RefershEvents.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        RefershEvents.setForeground(new java.awt.Color(255, 255, 255));
        RefershEvents.setText("Refresh");
        RefershEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefershEventsActionPerformed(evt);
            }
        });

        EditUserInfo.setBackground(new java.awt.Color(255, 51, 51));
        EditUserInfo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        EditUserInfo.setForeground(new java.awt.Color(255, 255, 255));
        EditUserInfo.setText("UserInformation");
        EditUserInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditUserInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dyanmicPanelLayout = new javax.swing.GroupLayout(dyanmicPanel);
        dyanmicPanel.setLayout(dyanmicPanelLayout);
        dyanmicPanelLayout.setHorizontalGroup(
            dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dyanmicPanelLayout.createSequentialGroup()
                .addContainerGap(807, Short.MAX_VALUE)
                .addComponent(Date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(dyanmicPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dyanmicPanelLayout.createSequentialGroup()
                        .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(dyanmicPanelLayout.createSequentialGroup()
                                .addComponent(CategoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(TotalEventsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TotalBookingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(66, 66, 66))
                    .addGroup(dyanmicPanelLayout.createSequentialGroup()
                        .addComponent(RefershEvents)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
        );
        dyanmicPanelLayout.setVerticalGroup(
            dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dyanmicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Date)
                    .addComponent(lbl_Time))
                .addGap(37, 37, 37)
                .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TotalEventsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(CategoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(TotalBookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RefershEvents)
                    .addComponent(EditUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MainPanel1Layout = new javax.swing.GroupLayout(MainPanel1);
        MainPanel1.setLayout(MainPanel1Layout);
        MainPanel1Layout.setHorizontalGroup(
            MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel1Layout.createSequentialGroup()
                .addComponent(SideTabPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dyanmicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanel1Layout.setVerticalGroup(
            MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel1Layout.createSequentialGroup()
                .addGroup(MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SideTabPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dyanmicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DashboardMousePressed
        // This will connect another tabbed window inside the same jframe

        //gowdie.Isobel [] Pets = new gowdie.Isobel[4];

    }//GEN-LAST:event_btn_DashboardMousePressed

    private void btn_ViewBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ViewBookingActionPerformed
        // TODO add your handling code here:
        
       AllBookings alf= new AllBookings();
        alf.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btn_ViewBookingActionPerformed

    private void btn_AddEventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddEventsMouseClicked
       

    }//GEN-LAST:event_btn_AddEventsMouseClicked

    private void btn_AddEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddEventsActionPerformed
        // TODO add your handling code here:
        //System.out.println("This is Closing function");
       
        
        AddEvents aed = new AddEvents();
        aed.setVisible(true);
        

    }//GEN-LAST:event_btn_AddEventsActionPerformed

    private void btn_AlterEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AlterEventsActionPerformed
        // TODO add your handling code here:
        EventAlter eav=new EventAlter();
        eav.setVisible(true);
       

    }//GEN-LAST:event_btn_AlterEventsActionPerformed

    private void btn_ViewUserLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ViewUserLogActionPerformed
        // This will enables the functions of change password
        
        
        ViewUserLog vf= new ViewUserLog();
        vf.setVisible(true);
       
    }//GEN-LAST:event_btn_ViewUserLogActionPerformed

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        
        KioskMain kgf = new KioskMain();
        kgf.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblLogoutMouseClicked

    private void IconLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconLogOutMouseClicked
        // TODO add your handling code here:
        
        KioskMain kgf = new KioskMain();
        kgf.setVisible(true);
        this.dispose();
     
    }//GEN-LAST:event_IconLogOutMouseClicked

    private void CategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CategoryItemStateChanged
        
        
        //String query=Category.getSelectedItem().toString();
        //filter(query);
    }//GEN-LAST:event_CategoryItemStateChanged

    private void txtTotalEventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalEventsMouseClicked
        // TODO add your handling code here:
        
         
       
    }//GEN-LAST:event_txtTotalEventsMouseClicked

    private void RefershEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefershEventsActionPerformed
        // TODO add your handling code here:
        EventList();
        TotalEvent();
        
    }//GEN-LAST:event_RefershEventsActionPerformed

    private void CategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CategoryKeyReleased
        // TODO add your handling code here:
        
        
       
    }//GEN-LAST:event_CategoryKeyReleased

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        
        TotalBook();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void EditUserInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditUserInfoActionPerformed
        // TODO add your handling code here:
        
        StudentInfo si=new StudentInfo();
        si.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_EditUserInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Category;
    private javax.swing.JPanel CategoryPanel;
    private javax.swing.JLabel Date;
    private javax.swing.JButton EditUserInfo;
    private javax.swing.JTable EventsList;
    private javax.swing.JLabel IconLogOut;
    private javax.swing.JPanel MainPanel1;
    private javax.swing.JButton RefershEvents;
    private javax.swing.JPanel SideTabPanel1;
    private javax.swing.JLabel TotalBook;
    private javax.swing.JPanel TotalBookingPanel;
    private javax.swing.JPanel TotalEventsPanel;
    private javax.swing.JLabel UniversityLogo1;
    private javax.swing.JButton btn_AddEvents;
    private javax.swing.JButton btn_AlterEvents;
    private javax.swing.JButton btn_Dashboard;
    private javax.swing.JButton btn_ViewBooking;
    private javax.swing.JButton btn_ViewUserLog;
    private javax.swing.JPanel category;
    private javax.swing.JPanel dyanmicPanel;
    private javax.swing.JLabel icon_help1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lbl_Date;
    private javax.swing.JLabel lbl_Time;
    private javax.swing.JLabel lbl_help1;
    private javax.swing.JLabel txtTotalEvents;
    // End of variables declaration//GEN-END:variables
}
