/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ujaalo;

import Events.EventsNormal;
import Courses.UnderGraduate;
import Student.OpenDays;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author User
 */
public class KioskMain extends javax.swing.JFrame {

    /**
     * Creates new form KioskMain
     */
    public KioskMain() {
        initComponents();
        
        
        ShowDate(); //Method For Showing Date in Jlabel named lbl_Date
        ShowTime(); //Method For Showing Time in JLabel named lbl_Time
    }

    //Method Showing Date
    void ShowDate(){
        
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        lbl_Date.setText(s.format(d));
        
    }
    
    
    void ShowTime(){
        new Timer(0,new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e){
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                lbl_Time.setText(s.format(d));
                   
            }  
        }
              
        ).start();
              
    }
    
    public void Campuses(){
        
        Campuses cgf = new Campuses(); //making a object/instance of campus class
        cgf.setVisible(true);
        this.dispose();
    }
    
    
    public void Courses(){
        Courses cos = new Courses();
        cos.setVisible(true);
        this.dispose();
        
    }
    
    public void EventsNormal(){
        
         EventsNormal ef= new EventsNormal();
        ef.setVisible(true);
        //this.dispose();
    }
    
    public void Register(){
         RegisterLogin rgf= new RegisterLogin();
        KioskMain kmr= new KioskMain();
        rgf.setVisible(true);
        kmr.dispose();
        
    }
    
    public void whyUs(){
        
         
    }
    
    public void Brochure(){
        
          try {
        Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "D:\\Java Project\\Ujaalo Kiosk\\src\\PdfFiles\\Course-Handbook-BSC-CSSE.pdf");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Error");
    }
    }
   
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SideTabPanel = new javax.swing.JPanel();
        UniversityLogo = new javax.swing.JLabel();
        btn_home = new javax.swing.JButton();
        btn_campuses = new javax.swing.JButton();
        btn_courses = new javax.swing.JButton();
        btn_events = new javax.swing.JButton();
        btn_stdLogin = new javax.swing.JButton();
        btn_Prospectus = new javax.swing.JButton();
        icon_help = new javax.swing.JLabel();
        lbl_help = new javax.swing.JLabel();
        dyanmicPanel = new javax.swing.JPanel();
        our_courses1 = new javax.swing.JLabel();
        our_courses2 = new javax.swing.JLabel();
        our_courses3 = new javax.swing.JLabel();
        btn_postGraduate = new javax.swing.JButton();
        btn_underGraduate = new javax.swing.JButton();
        btn_nternationalStd = new javax.swing.JButton();
        our_courses4 = new javax.swing.JLabel();
        btn_girlsSTEM = new javax.swing.JButton();
        Events = new javax.swing.JLabel();
        btn_Events = new javax.swing.JButton();
        our_courses6 = new javax.swing.JLabel();
        our_courses7 = new javax.swing.JLabel();
        opendays = new javax.swing.JButton();
        jobPlacements = new javax.swing.JButton();
        our_courses8 = new javax.swing.JLabel();
        whyus = new javax.swing.JButton();
        btn_more = new javax.swing.JLabel();
        lbl_more = new javax.swing.JLabel();
        ImageSlider = new javax.swing.JLabel();
        lbl_Time = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        lbl_Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        NextSlider = new javax.swing.JLabel();
        PreviousSlider = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));

        MainPanel.setBackground(new java.awt.Color(99, 110, 114));
        MainPanel.setMaximumSize(new java.awt.Dimension(1366, 768));
        MainPanel.setMinimumSize(new java.awt.Dimension(1366, 768));
        MainPanel.setPreferredSize(new java.awt.Dimension(1366, 768));

        SideTabPanel.setBackground(new java.awt.Color(237, 28, 36));
        SideTabPanel.setMaximumSize(new java.awt.Dimension(270, 768));
        SideTabPanel.setMinimumSize(new java.awt.Dimension(270, 768));
        SideTabPanel.setPreferredSize(new java.awt.Dimension(270, 768));

        UniversityLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/uu1.png"))); // NOI18N

        btn_home.setBackground(new java.awt.Color(237, 28, 36));
        btn_home.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/about.png"))); // NOI18N
        btn_home.setText("     Home       ");
        btn_home.setBorder(null);
        btn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_homeMousePressed(evt);
            }
        });
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        btn_campuses.setBackground(new java.awt.Color(237, 28, 36));
        btn_campuses.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_campuses.setForeground(new java.awt.Color(255, 255, 255));
        btn_campuses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Campus.png"))); // NOI18N
        btn_campuses.setText("     Campuses");
        btn_campuses.setBorder(null);
        btn_campuses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_campuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_campusesActionPerformed(evt);
            }
        });

        btn_courses.setBackground(new java.awt.Color(237, 28, 36));
        btn_courses.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_courses.setForeground(new java.awt.Color(255, 255, 255));
        btn_courses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coursess.png.png"))); // NOI18N
        btn_courses.setText("       Courses ");
        btn_courses.setBorder(null);
        btn_courses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_coursesActionPerformed(evt);
            }
        });

        btn_events.setBackground(new java.awt.Color(237, 28, 36));
        btn_events.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_events.setForeground(new java.awt.Color(255, 255, 255));
        btn_events.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/apply.png"))); // NOI18N
        btn_events.setText("         Events    ");
        btn_events.setBorder(null);
        btn_events.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_events.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eventsActionPerformed(evt);
            }
        });

        btn_stdLogin.setBackground(new java.awt.Color(237, 28, 36));
        btn_stdLogin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_stdLogin.setForeground(new java.awt.Color(255, 255, 255));
        btn_stdLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/StudentLogin.png"))); // NOI18N
        btn_stdLogin.setText("         Login   ");
        btn_stdLogin.setBorder(null);
        btn_stdLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_stdLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stdLoginActionPerformed(evt);
            }
        });

        btn_Prospectus.setBackground(new java.awt.Color(237, 28, 36));
        btn_Prospectus.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_Prospectus.setForeground(new java.awt.Color(255, 255, 255));
        btn_Prospectus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Prospectus.png"))); // NOI18N
        btn_Prospectus.setText("      Brochure");
        btn_Prospectus.setBorder(null);
        btn_Prospectus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Prospectus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProspectusActionPerformed(evt);
            }
        });

        icon_help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/help.png"))); // NOI18N
        icon_help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_helpMouseClicked(evt);
            }
        });

        lbl_help.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_help.setForeground(new java.awt.Color(255, 255, 255));
        lbl_help.setText("Help");
        lbl_help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_helpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SideTabPanelLayout = new javax.swing.GroupLayout(SideTabPanel);
        SideTabPanel.setLayout(SideTabPanelLayout);
        SideTabPanelLayout.setHorizontalGroup(
            SideTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_campuses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_courses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_events, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_stdLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_Prospectus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideTabPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(SideTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideTabPanelLayout.createSequentialGroup()
                        .addComponent(UniversityLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideTabPanelLayout.createSequentialGroup()
                        .addComponent(icon_help)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_help)
                        .addGap(31, 31, 31))))
        );
        SideTabPanelLayout.setVerticalGroup(
            SideTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideTabPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(UniversityLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_campuses, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_courses, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_events, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_stdLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Prospectus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(SideTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(icon_help, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_help, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        dyanmicPanel.setBackground(new java.awt.Color(99, 110, 114));
        dyanmicPanel.setMaximumSize(new java.awt.Dimension(1090, 768));
        dyanmicPanel.setMinimumSize(new java.awt.Dimension(1090, 768));

        our_courses1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/international12.jpg"))); // NOI18N
        our_courses1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        our_courses2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UnderGrad2.jpg"))); // NOI18N
        our_courses2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        our_courses2.setPreferredSize(new java.awt.Dimension(311, 200));

        our_courses3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PG3.jpg"))); // NOI18N
        our_courses3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        our_courses3.setMaximumSize(new java.awt.Dimension(313, 200));
        our_courses3.setMinimumSize(new java.awt.Dimension(313, 200));
        our_courses3.setPreferredSize(new java.awt.Dimension(313, 200));

        btn_postGraduate.setBackground(new java.awt.Color(99, 110, 114));
        btn_postGraduate.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_postGraduate.setForeground(new java.awt.Color(255, 255, 255));
        btn_postGraduate.setText("Postgraduate Courses");
        btn_postGraduate.setBorder(null);
        btn_postGraduate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_postGraduate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_postGraduateActionPerformed(evt);
            }
        });

        btn_underGraduate.setBackground(new java.awt.Color(99, 110, 114));
        btn_underGraduate.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_underGraduate.setForeground(new java.awt.Color(255, 255, 255));
        btn_underGraduate.setText("Undergraduate Courses");
        btn_underGraduate.setBorder(null);
        btn_underGraduate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_underGraduate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_underGraduateActionPerformed(evt);
            }
        });

        btn_nternationalStd.setBackground(new java.awt.Color(99, 110, 114));
        btn_nternationalStd.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_nternationalStd.setForeground(new java.awt.Color(255, 255, 255));
        btn_nternationalStd.setText("International Students");
        btn_nternationalStd.setBorder(null);
        btn_nternationalStd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nternationalStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nternationalStdActionPerformed(evt);
            }
        });

        our_courses4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/morethandegree.jpg"))); // NOI18N
        our_courses4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        btn_girlsSTEM.setBackground(new java.awt.Color(99, 110, 114));
        btn_girlsSTEM.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_girlsSTEM.setForeground(new java.awt.Color(255, 255, 255));
        btn_girlsSTEM.setText("Girls In STEM");
        btn_girlsSTEM.setBorder(null);
        btn_girlsSTEM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_girlsSTEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girlsSTEMActionPerformed(evt);
            }
        });

        Events.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/foundation.jpg"))); // NOI18N
        Events.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        Events.setPreferredSize(new java.awt.Dimension(311, 200));

        btn_Events.setBackground(new java.awt.Color(99, 110, 114));
        btn_Events.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_Events.setForeground(new java.awt.Color(255, 255, 255));
        btn_Events.setText("Foundation Year");
        btn_Events.setBorder(null);
        btn_Events.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Events.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EventsActionPerformed(evt);
            }
        });

        our_courses6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/job1.jpg"))); // NOI18N
        our_courses6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        our_courses6.setMaximumSize(new java.awt.Dimension(313, 200));
        our_courses6.setMinimumSize(new java.awt.Dimension(313, 200));
        our_courses6.setPreferredSize(new java.awt.Dimension(313, 200));

        our_courses7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/openday.jpg"))); // NOI18N
        our_courses7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        opendays.setBackground(new java.awt.Color(99, 110, 114));
        opendays.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        opendays.setForeground(new java.awt.Color(255, 255, 255));
        opendays.setText("Open Days");
        opendays.setBorder(null);
        opendays.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opendays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opendaysActionPerformed(evt);
            }
        });

        jobPlacements.setBackground(new java.awt.Color(99, 110, 114));
        jobPlacements.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jobPlacements.setForeground(new java.awt.Color(255, 255, 255));
        jobPlacements.setText("Job Placements");
        jobPlacements.setBorder(null);
        jobPlacements.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jobPlacements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobPlacementsActionPerformed(evt);
            }
        });

        our_courses8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/whyus1.jpg"))); // NOI18N
        our_courses8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        whyus.setBackground(new java.awt.Color(99, 110, 114));
        whyus.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        whyus.setForeground(new java.awt.Color(255, 255, 255));
        whyus.setText("Why Us");
        whyus.setBorder(null);
        whyus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        whyus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whyusActionPerformed(evt);
            }
        });

        btn_more.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/more.png"))); // NOI18N

        lbl_more.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_more.setForeground(new java.awt.Color(255, 255, 255));
        lbl_more.setText("More...");
        lbl_more.setPreferredSize(new java.awt.Dimension(26, 22));

        ImageSlider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Webp.net-gifmaker.gif"))); // NOI18N

        lbl_Time.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbl_Time.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Time.setText("Time");

        Date.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 255, 255));
        Date.setText("Date");

        lbl_Date.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbl_Date.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Date.setText("Date");

        Time.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Time.setForeground(new java.awt.Color(255, 255, 255));
        Time.setText("Time");

        NextSlider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/next.png"))); // NOI18N

        PreviousSlider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back1.png"))); // NOI18N

        javax.swing.GroupLayout dyanmicPanelLayout = new javax.swing.GroupLayout(dyanmicPanel);
        dyanmicPanel.setLayout(dyanmicPanelLayout);
        dyanmicPanelLayout.setHorizontalGroup(
            dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dyanmicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dyanmicPanelLayout.createSequentialGroup()
                        .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dyanmicPanelLayout.createSequentialGroup()
                                .addComponent(Events, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(dyanmicPanelLayout.createSequentialGroup()
                                .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_Events, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(btn_underGraduate, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(our_courses2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dyanmicPanelLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jobPlacements, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dyanmicPanelLayout.createSequentialGroup()
                                        .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(our_courses3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_postGraduate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(2, 2, 2))
                                    .addGroup(dyanmicPanelLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(our_courses6, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dyanmicPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(opendays, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(whyus, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dyanmicPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(our_courses1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_nternationalStd, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dyanmicPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(our_courses4))
                                    .addGroup(dyanmicPanelLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(btn_girlsSTEM, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(dyanmicPanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(our_courses7, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(our_courses8)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dyanmicPanelLayout.createSequentialGroup()
                        .addComponent(Date)
                        .addGap(28, 28, 28)
                        .addComponent(lbl_Date)
                        .addGap(37, 37, 37)
                        .addComponent(Time)
                        .addGap(26, 26, 26)
                        .addComponent(lbl_Time)
                        .addGap(318, 318, 318)
                        .addComponent(btn_more)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_more, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dyanmicPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PreviousSlider)
                .addGap(27, 27, 27)
                .addComponent(ImageSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(NextSlider)
                .addGap(67, 67, 67))
        );
        dyanmicPanelLayout.setVerticalGroup(
            dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dyanmicPanelLayout.createSequentialGroup()
                .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dyanmicPanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(PreviousSlider))
                    .addGroup(dyanmicPanelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(NextSlider))
                    .addComponent(ImageSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(dyanmicPanelLayout.createSequentialGroup()
                        .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dyanmicPanelLayout.createSequentialGroup()
                                .addComponent(our_courses2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_underGraduate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dyanmicPanelLayout.createSequentialGroup()
                                .addComponent(our_courses3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_postGraduate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(our_courses6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Events, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dyanmicPanelLayout.createSequentialGroup()
                        .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(our_courses1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(our_courses4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_girlsSTEM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_nternationalStd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(our_courses8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(our_courses7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Events, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opendays, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jobPlacements, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whyus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_more)
                    .addComponent(lbl_more, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dyanmicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_Date)
                        .addComponent(Date)
                        .addComponent(Time)
                        .addComponent(lbl_Time)))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(SideTabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dyanmicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideTabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dyanmicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btn_campusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_campusesActionPerformed
        // TODO add your handling code here:
        
        Campuses cgf = new Campuses();
        cgf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_campusesActionPerformed

    private void btn_coursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_coursesActionPerformed
        // TODO add your handling code here:
        Courses cos = new Courses();
        cos.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_btn_coursesActionPerformed

    private void btn_eventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eventsActionPerformed
        // TODO add your handling code here:
        
         EventsNormal ef= new EventsNormal();
        ef.setVisible(true);
        //this.dispose();
            
    }//GEN-LAST:event_btn_eventsActionPerformed

    private void btn_stdLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stdLoginActionPerformed
        // TODO add your handling code here:
        RegisterLogin rgf= new RegisterLogin();
        KioskMain kmr= new KioskMain();
        rgf.setVisible(true);
        kmr.dispose();
    }//GEN-LAST:event_btn_stdLoginActionPerformed

    private void btn_ProspectusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProspectusActionPerformed
        // TODO add your handling code here:
          try {
        Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "D:\\Java Project\\Ujaalo Kiosk\\src\\PdfFiles\\Course-Handbook-BSC-CSSE.pdf");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Error");
    }
        
          
          //D:\Java Project\Ujaalo Kiosk\src\PdfFiles\help.pdf
    }//GEN-LAST:event_btn_ProspectusActionPerformed

    private void btn_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMousePressed
        // This will connect another tabbed window inside the same jframe
        
        
        
        
    }//GEN-LAST:event_btn_homeMousePressed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        
        KioskMain kgf = new KioskMain();
        kgf.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_underGraduateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_underGraduateActionPerformed
        // TODO add your handling code here:
        
        Courses cos = new Courses();
        cos.setVisible(true);
        this.dispose();
        
        
        
    }//GEN-LAST:event_btn_underGraduateActionPerformed

    private void btn_postGraduateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_postGraduateActionPerformed
        // TODO add your handling code here:
        
        Courses cos = new Courses();
        cos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_postGraduateActionPerformed

    private void btn_nternationalStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nternationalStdActionPerformed
        // TODO add your handling code here:
        
        
        Courses cos = new Courses();
        cos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_nternationalStdActionPerformed

    private void btn_EventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EventsActionPerformed
        // TODO add your handling code here:
        
        Courses cos = new Courses();
        cos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_EventsActionPerformed

    private void jobPlacementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobPlacementsActionPerformed
        // TODO add your handling code here:
      WhyUs why = new WhyUs();
      why.setVisible(true);
      this.dispose();
      
    
    }//GEN-LAST:event_jobPlacementsActionPerformed

    private void icon_helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_helpMouseClicked
        // TODO add your handling code here:
        
        
        try {
        Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "D:\\Java Project\\Ujaalo Kiosk\\src\\PdfFiles\\help.pdf");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Error");
    }
    }//GEN-LAST:event_icon_helpMouseClicked

    private void lbl_helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_helpMouseClicked
        // TODO add your handling code here:
        
         try {
        Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "D:\\Java Project\\Ujaalo Kiosk\\src\\PdfFiles\\help.pdf");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Error");
    }
    }//GEN-LAST:event_lbl_helpMouseClicked

    private void whyusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whyusActionPerformed
        // TODO add your handling code here:
        
      WhyUs why = new WhyUs();
      why.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_whyusActionPerformed

    private void opendaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opendaysActionPerformed
        // TODO add your handling code here:
        
           OpenDays why = new OpenDays();
      why.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_opendaysActionPerformed

    private void btn_girlsSTEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girlsSTEMActionPerformed
        // TODO add your handling code here:
        
         WhyUs why = new WhyUs();
      why.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btn_girlsSTEMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KioskMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KioskMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KioskMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KioskMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KioskMain().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Events;
    private javax.swing.JLabel ImageSlider;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel NextSlider;
    private javax.swing.JLabel PreviousSlider;
    private javax.swing.JPanel SideTabPanel;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel UniversityLogo;
    private javax.swing.JButton btn_Events;
    private javax.swing.JButton btn_Prospectus;
    private javax.swing.JButton btn_campuses;
    private javax.swing.JButton btn_courses;
    private javax.swing.JButton btn_events;
    private javax.swing.JButton btn_girlsSTEM;
    private javax.swing.JButton btn_home;
    private javax.swing.JLabel btn_more;
    private javax.swing.JButton btn_nternationalStd;
    private javax.swing.JButton btn_postGraduate;
    private javax.swing.JButton btn_stdLogin;
    private javax.swing.JButton btn_underGraduate;
    private javax.swing.JPanel dyanmicPanel;
    private javax.swing.JLabel icon_help;
    private javax.swing.JButton jobPlacements;
    private javax.swing.JLabel lbl_Date;
    private javax.swing.JLabel lbl_Time;
    private javax.swing.JLabel lbl_help;
    private javax.swing.JLabel lbl_more;
    private javax.swing.JButton opendays;
    private javax.swing.JLabel our_courses1;
    private javax.swing.JLabel our_courses2;
    private javax.swing.JLabel our_courses3;
    private javax.swing.JLabel our_courses4;
    private javax.swing.JLabel our_courses6;
    private javax.swing.JLabel our_courses7;
    private javax.swing.JLabel our_courses8;
    private javax.swing.JButton whyus;
    // End of variables declaration//GEN-END:variables
}
