/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ujaalo;

import java.sql.Connection;
import java.text.DateFormat;
import java.text.ParseException;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

//Thsese are the libraies used for date and time
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Kshitij Bajagain
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form REgister
     * 
     * 
     */
    
    
     Connection conn=null;
    OraclePreparedStatement pst=null;
    OracleResultSet rs = null;
    
    
    
    
    
    
    public Login() {
        initComponents();
        
        
    }
    
    
    public void login(){
        conn = OracleDatabase.ConnectDb();
        String userID = txt_unID.getText();
        String email = txt_email.getText();
        String pass = txt_pass.getText();
       
        
     


  

       
       try{
           
           String sql = "SELECT * FROM Student WHERE UniversityID=? AND StdEmail=? AND Password=?";
           pst = (OraclePreparedStatement) conn.prepareStatement(sql);
           pst.setString(1,userID);
           pst.setString(2,email);
           pst.setString(3,pass);
           
           
           rs =(OracleResultSet) pst.executeQuery();
           
           if (rs.next())
           {
               JOptionPane.showMessageDialog(null,"Login Successful.Now you will be redirected to your Home Page");
               
                
               StudentDashboard sgf= new StudentDashboard();
                sgf.setVisible(true);
                this.dispose();
                
                
                
           }
           else
           {
               JOptionPane.showMessageDialog(null,"Login Unsuccessful.Try again with correct credentials.");
           }
           
       }
       catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
       
       
        
        
    }
    public void UserLog(){
        
        conn = OracleDatabase.ConnectDb();
        String userID = txt_unID.getText();
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        
         String date = s.format(d);
        
        try{
           
           String sql = "INSERT INTO  SessionManagement(UniversityID,Login_Date) VALUES(?,?)";
           pst = (OraclePreparedStatement) conn.prepareStatement(sql);
           pst.setString(1,userID);
           pst.setString(2,date);
           
           
           
           
           
           rs =(OracleResultSet) pst.executeQuery();
           
          
           
       }
       catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
       
       
        
        
        
        
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterLoginMain = new javax.swing.JPanel();
        RegisterName = new javax.swing.JLabel();
        SideLogin = new javax.swing.JPanel();
        RegisterLoginIcon = new javax.swing.JLabel();
        Cancel = new javax.swing.JLabel();
        BackPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        UniversityID = new javax.swing.JLabel();
        EmailAddress = new javax.swing.JLabel();
        txt_unID = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        UniversityIDSeparator = new javax.swing.JSeparator();
        UniversityIDSeparator1 = new javax.swing.JSeparator();
        UniIcon = new javax.swing.JLabel();
        EmailIcon = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        PasswordIcon = new javax.swing.JLabel();
        UniversityIDSeparator2 = new javax.swing.JSeparator();
        txt_pass = new javax.swing.JPasswordField();
        AdminLoginRedirect = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        RegisterLoginMain.setBackground(new java.awt.Color(255, 255, 255));
        RegisterLoginMain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        RegisterLoginMain.setPreferredSize(new java.awt.Dimension(700, 509));

        RegisterName.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        RegisterName.setForeground(new java.awt.Color(214, 48, 49));
        RegisterName.setText("Login Page");

        SideLogin.setBackground(new java.awt.Color(214, 48, 49));

        RegisterLoginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLogin.png"))); // NOI18N

        Cancel.setBackground(new java.awt.Color(214, 48, 49));
        Cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cancel.setForeground(new java.awt.Color(255, 255, 255));
        Cancel.setText("Ujaalo Kiosk");

        javax.swing.GroupLayout SideLoginLayout = new javax.swing.GroupLayout(SideLogin);
        SideLogin.setLayout(SideLoginLayout);
        SideLoginLayout.setHorizontalGroup(
            SideLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideLoginLayout.createSequentialGroup()
                .addGroup(SideLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideLoginLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(RegisterLoginIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SideLoginLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(Cancel)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        SideLoginLayout.setVerticalGroup(
            SideLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideLoginLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(RegisterLoginIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Cancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BackPanel.setBackground(new java.awt.Color(214, 48, 49));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BackPanelLayout = new javax.swing.GroupLayout(BackPanel);
        BackPanel.setLayout(BackPanelLayout);
        BackPanelLayout.setHorizontalGroup(
            BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackPanelLayout.setVerticalGroup(
            BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        UniversityID.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        UniversityID.setForeground(new java.awt.Color(214, 48, 49));
        UniversityID.setText("University ID");

        EmailAddress.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        EmailAddress.setForeground(new java.awt.Color(214, 48, 49));
        EmailAddress.setText("Email");

        txt_unID.setBackground(new java.awt.Color(255, 255, 255));
        txt_unID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_unID.setForeground(new java.awt.Color(102, 102, 102));
        txt_unID.setBorder(null);

        txt_email.setBackground(new java.awt.Color(255, 255, 255));
        txt_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(102, 102, 102));
        txt_email.setBorder(null);
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_emailKeyPressed(evt);
            }
        });

        UniversityIDSeparator.setBackground(new java.awt.Color(153, 153, 153));
        UniversityIDSeparator.setForeground(new java.awt.Color(153, 153, 153));
        UniversityIDSeparator.setMaximumSize(new java.awt.Dimension(261, 24));
        UniversityIDSeparator.setMinimumSize(new java.awt.Dimension(261, 24));
        UniversityIDSeparator.setPreferredSize(new java.awt.Dimension(261, 24));

        UniversityIDSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        UniversityIDSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        UniversityIDSeparator1.setMaximumSize(new java.awt.Dimension(261, 24));
        UniversityIDSeparator1.setMinimumSize(new java.awt.Dimension(261, 24));
        UniversityIDSeparator1.setPreferredSize(new java.awt.Dimension(261, 24));

        UniIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/University ID.png"))); // NOI18N

        EmailIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gm.png"))); // NOI18N

        Password.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Password.setForeground(new java.awt.Color(214, 48, 49));
        Password.setText("Password");

        PasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Password.png"))); // NOI18N

        UniversityIDSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        UniversityIDSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        UniversityIDSeparator2.setMaximumSize(new java.awt.Dimension(261, 24));
        UniversityIDSeparator2.setMinimumSize(new java.awt.Dimension(261, 24));
        UniversityIDSeparator2.setPreferredSize(new java.awt.Dimension(261, 24));

        txt_pass.setBackground(new java.awt.Color(255, 255, 255));
        txt_pass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(102, 102, 102));
        txt_pass.setBorder(null);

        AdminLoginRedirect.setBackground(new java.awt.Color(0, 0, 0));
        AdminLoginRedirect.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AdminLoginRedirect.setForeground(new java.awt.Color(214, 48, 49));
        AdminLoginRedirect.setText("Are you Admin? Then Login as Admin");
        AdminLoginRedirect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminLoginRedirect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminLoginRedirectMouseClicked(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(214, 48, 49));
        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.setBorder(null);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterLoginMainLayout = new javax.swing.GroupLayout(RegisterLoginMain);
        RegisterLoginMain.setLayout(RegisterLoginMainLayout);
        RegisterLoginMainLayout.setHorizontalGroup(
            RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                .addComponent(SideLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLoginMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BackPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLoginMainLayout.createSequentialGroup()
                                .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                                        .addComponent(UniversityID)
                                        .addGap(226, 226, 226))
                                    .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                                        .addComponent(EmailAddress)
                                        .addGap(281, 281, 281))
                                    .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                                            .addComponent(UniIcon)
                                            .addGap(37, 37, 37)
                                            .addComponent(txt_unID, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(UniversityIDSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(UniversityIDSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Password)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLoginMainLayout.createSequentialGroup()
                                                .addComponent(PasswordIcon)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                                                .addComponent(EmailIcon)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(UniversityIDSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(61, 61, 61))))
                    .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                        .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(RegisterName))
                            .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(AdminLoginRedirect)))
                        .addContainerGap())))
        );
        RegisterLoginMainLayout.setVerticalGroup(
            RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                .addComponent(BackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(RegisterName)
                .addGap(39, 39, 39)
                .addComponent(UniversityID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UniIcon)
                    .addComponent(txt_unID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UniversityIDSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UniversityIDSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UniversityIDSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(AdminLoginRedirect)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterLoginMain, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterLoginMain, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(705, 534));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        this.setVisible(false);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void AdminLoginRedirectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLoginRedirectMouseClicked
        // Connecting with Register Page
        
        AdminLogin alf= new AdminLogin();
        alf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdminLoginRedirectMouseClicked

    private void txt_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailKeyPressed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
           
        /**
        conn = OracleDatabase.ConnectDb();
        String userID = txt_unID.getText();
        String email = txt_email.getText();
        String pass = txt_pass.getText();
       
        
     


  

       
       try{
           
           String sql = "SELECT * FROM Student WHERE UniversityID=? AND StdEmail=? AND Password=?";
           pst = (OraclePreparedStatement) conn.prepareStatement(sql);
           pst.setString(1,userID);
           pst.setString(2,email);
           pst.setString(3,pass);
           
           
           rs =(OracleResultSet) pst.executeQuery();
           
           if (rs.next())
           {
               JOptionPane.showMessageDialog(null,"Login Successful.Now you will be redirected to your Home Page");
               
                
               StudentDashboard sgf= new StudentDashboard();
                sgf.setVisible(true);
                this.dispose();
                
                
                
           }
           else
           {
               JOptionPane.showMessageDialog(null,"Login Unsuccessful.Try again with correct credentials.");
           }
           
       }
       catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
       
       **/
       
            login();
           UserLog();
        
        

       
      
    }//GEN-LAST:event_loginBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminLoginRedirect;
    private javax.swing.JPanel BackPanel;
    private javax.swing.JLabel Cancel;
    private javax.swing.JLabel EmailAddress;
    private javax.swing.JLabel EmailIcon;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel PasswordIcon;
    private javax.swing.JLabel RegisterLoginIcon;
    private javax.swing.JPanel RegisterLoginMain;
    private javax.swing.JLabel RegisterName;
    private javax.swing.JPanel SideLogin;
    private javax.swing.JLabel UniIcon;
    private javax.swing.JLabel UniversityID;
    private javax.swing.JSeparator UniversityIDSeparator;
    private javax.swing.JSeparator UniversityIDSeparator1;
    private javax.swing.JSeparator UniversityIDSeparator2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginBtn;
    public static javax.swing.JTextField txt_email;
    public static javax.swing.JPasswordField txt_pass;
    public static javax.swing.JTextField txt_unID;
    // End of variables declaration//GEN-END:variables
}
