package Ujaalo;

import java.sql.Connection;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kshitij Bajagain
 */
public class RegisterLogin extends javax.swing.JFrame {
    
    
    //This is the part of  oracle  database connectivity
    
    Connection conn=null;
    OraclePreparedStatement pst=null;
    OracleResultSet rs = null;
    
    
    

    /**
     * Creates new form RegisterLogin
     */
    public RegisterLogin() {
        initComponents();
        CoursePopulate();
    }

    
    
    public void Register(){
        
        conn = OracleDatabase.ConnectDb();
       
       try{
           
           String sql = "insert into Student (UniversityID,StdName,StdEmail,Password,EnrolledCourse) values(?,?,?,?,?)";
           pst = (OraclePreparedStatement) conn.prepareStatement(sql);
           pst.setString(1,txt_UniID.getText());
           pst.setString(2,FullName.getText());
           pst.setString(3,txt_Email.getText());
           pst.setString(4,txt_Password.getText());
          // pst.setString(5,txt_EnrolledCourses.getText());
           
           rs =(OracleResultSet) pst.executeQuery();
           
           if (rs.next())
           {
               JOptionPane.showMessageDialog(null,"Registeration Successful.Now you will be redirected to login page");
               
                Login lgf = new Login();
                lgf.setVisible(true);
                this.dispose();
           }
           
           else
           {
               JOptionPane.showMessageDialog(null,"Registeration Unsuccessful.Please fill the registeration form carefully!!");
           }
          
       }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    
    
    
    
    public void CoursePopulate(){
        conn = OracleDatabase.ConnectDb();
       
       try{
           
           String sql = "SELECT CourseName FROM Course";
           pst = (OraclePreparedStatement) conn.prepareStatement(sql);
           
           
            
           
           rs =(OracleResultSet) pst.executeQuery();
          while(rs.next())
           {
               txt_EnrolledCourses.addItem(rs.getString(1));
               
                
           } 
          
          
       }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
        
    }
    
    
    public void EnrollCourse(){
        
        conn = OracleDatabase.ConnectDb();
       
       try{
           
           String sql = "insert into EnrolledCourse (UniversityID,CourseName) values(?,?)";
           pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1,txt_UniID.getText());
            
            String value = txt_EnrolledCourses.getSelectedItem().toString();
           pst.setString(2,value);
           
           rs =(OracleResultSet) pst.executeQuery();
           
           
          
       }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    
    
    
    // This is a boolean static class that can be called by any classes inside Ujaalo Package 
    public static boolean validateEmail(String email) {                 

       boolean status=false;
      
       String EMAIL_PATTERN = 
  "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
  + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
       Pattern pattern = Pattern.compile(EMAIL_PATTERN);
       Matcher matcher=pattern.matcher(email);
       if(matcher.matches())
       {
           status=true;
       }
       else{
           status=false;
       }
           return status;
            
    }
    
   
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterLoginMain = new javax.swing.JPanel();
        RegisterName = new javax.swing.JLabel();
        SideLogin = new javax.swing.JPanel();
        RegisterLoginIcon = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BackPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_UniversityID = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        txt_UniID = new javax.swing.JTextField();
        UniversityIDSeparator = new javax.swing.JSeparator();
        UniversityIDSeparator1 = new javax.swing.JSeparator();
        uniIcon = new javax.swing.JLabel();
        FullNameIcon = new javax.swing.JLabel();
        lbl_Password = new javax.swing.JLabel();
        passwordIcon = new javax.swing.JLabel();
        UniversityIDSeparator2 = new javax.swing.JSeparator();
        txt_Password = new javax.swing.JPasswordField();
        lbl_Already = new javax.swing.JLabel();
        lbl_enrolledCourse = new javax.swing.JLabel();
        EnrollIcon = new javax.swing.JLabel();
        lbl_validate = new javax.swing.JLabel();
        lbl_Email1 = new javax.swing.JLabel();
        EmailIcon = new javax.swing.JLabel();
        FullName = new javax.swing.JTextField();
        UniversityIDSeparator4 = new javax.swing.JSeparator();
        txt_Email = new javax.swing.JTextField();
        btn_register1 = new javax.swing.JButton();
        txt_EnrolledCourses = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        RegisterLoginMain.setBackground(new java.awt.Color(255, 255, 255));
        RegisterLoginMain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        RegisterLoginMain.setPreferredSize(new java.awt.Dimension(700, 509));

        RegisterName.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        RegisterName.setForeground(new java.awt.Color(214, 48, 49));
        RegisterName.setText("Register");

        SideLogin.setBackground(new java.awt.Color(214, 48, 49));

        RegisterLoginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLogin.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(214, 48, 49));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ujaalo Kiosk");

        javax.swing.GroupLayout SideLoginLayout = new javax.swing.GroupLayout(SideLogin);
        SideLogin.setLayout(SideLoginLayout);
        SideLoginLayout.setHorizontalGroup(
            SideLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideLoginLayout.createSequentialGroup()
                .addGroup(SideLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideLoginLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(RegisterLoginIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SideLoginLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        SideLoginLayout.setVerticalGroup(
            SideLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideLoginLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(RegisterLoginIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BackPanel.setBackground(new java.awt.Color(214, 48, 49));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BackPanelLayout = new javax.swing.GroupLayout(BackPanel);
        BackPanel.setLayout(BackPanelLayout);
        BackPanelLayout.setHorizontalGroup(
            BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackPanelLayout.setVerticalGroup(
            BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        lbl_UniversityID.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lbl_UniversityID.setForeground(new java.awt.Color(214, 48, 49));
        lbl_UniversityID.setText("University ID");

        lbl_Email.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lbl_Email.setForeground(new java.awt.Color(214, 48, 49));
        lbl_Email.setText("Full Name");

        txt_UniID.setBackground(new java.awt.Color(255, 255, 255));
        txt_UniID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_UniID.setForeground(new java.awt.Color(102, 102, 102));
        txt_UniID.setBorder(null);
        txt_UniID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_UniIDKeyPressed(evt);
            }
        });

        UniversityIDSeparator.setBackground(new java.awt.Color(153, 153, 153));
        UniversityIDSeparator.setForeground(new java.awt.Color(153, 153, 153));
        UniversityIDSeparator.setMaximumSize(new java.awt.Dimension(261, 24));
        UniversityIDSeparator.setMinimumSize(new java.awt.Dimension(261, 24));
        UniversityIDSeparator.setPreferredSize(new java.awt.Dimension(261, 24));

        UniversityIDSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        UniversityIDSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        UniversityIDSeparator1.setMaximumSize(new java.awt.Dimension(261, 24));
        UniversityIDSeparator1.setMinimumSize(new java.awt.Dimension(261, 24));
        UniversityIDSeparator1.setPreferredSize(new java.awt.Dimension(261, 24));

        uniIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/University ID.png"))); // NOI18N

        FullNameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fullName.png"))); // NOI18N

        lbl_Password.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lbl_Password.setForeground(new java.awt.Color(214, 48, 49));
        lbl_Password.setText("Password");

        passwordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Password.png"))); // NOI18N

        UniversityIDSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        UniversityIDSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        UniversityIDSeparator2.setMaximumSize(new java.awt.Dimension(261, 24));
        UniversityIDSeparator2.setMinimumSize(new java.awt.Dimension(261, 24));
        UniversityIDSeparator2.setPreferredSize(new java.awt.Dimension(261, 24));

        txt_Password.setBackground(new java.awt.Color(255, 255, 255));
        txt_Password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Password.setForeground(new java.awt.Color(102, 102, 102));
        txt_Password.setBorder(null);
        txt_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_PasswordKeyPressed(evt);
            }
        });

        lbl_Already.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Already.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Already.setForeground(new java.awt.Color(214, 48, 49));
        lbl_Already.setText("Already Registered? Login Now");
        lbl_Already.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Already.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_AlreadyMouseClicked(evt);
            }
        });

        lbl_enrolledCourse.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lbl_enrolledCourse.setForeground(new java.awt.Color(214, 48, 49));
        lbl_enrolledCourse.setText("Enrolled Course");

        EnrollIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Name.png"))); // NOI18N

        lbl_validate.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_validate.setForeground(new java.awt.Color(255, 0, 51));
        lbl_validate.setText("*One or more required information is empty.");

        lbl_Email1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lbl_Email1.setForeground(new java.awt.Color(214, 48, 49));
        lbl_Email1.setText("Email");

        EmailIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gm.png"))); // NOI18N

        FullName.setBackground(new java.awt.Color(255, 255, 255));
        FullName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FullName.setForeground(new java.awt.Color(102, 102, 102));
        FullName.setBorder(null);
        FullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullNameActionPerformed(evt);
            }
        });
        FullName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FullNameKeyPressed(evt);
            }
        });

        UniversityIDSeparator4.setBackground(new java.awt.Color(153, 153, 153));
        UniversityIDSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        UniversityIDSeparator4.setMaximumSize(new java.awt.Dimension(261, 24));
        UniversityIDSeparator4.setMinimumSize(new java.awt.Dimension(261, 24));
        UniversityIDSeparator4.setPreferredSize(new java.awt.Dimension(261, 24));

        txt_Email.setBackground(new java.awt.Color(255, 255, 255));
        txt_Email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Email.setForeground(new java.awt.Color(102, 102, 102));
        txt_Email.setBorder(null);
        txt_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmailActionPerformed(evt);
            }
        });
        txt_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_EmailKeyPressed(evt);
            }
        });

        btn_register1.setBackground(new java.awt.Color(214, 48, 49));
        btn_register1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btn_register1.setForeground(new java.awt.Color(255, 255, 255));
        btn_register1.setText("Register");
        btn_register1.setBorder(null);
        btn_register1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_register1ActionPerformed(evt);
            }
        });

        txt_EnrolledCourses.setBackground(new java.awt.Color(255, 255, 255));
        txt_EnrolledCourses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_EnrolledCourses.setForeground(new java.awt.Color(102, 102, 102));
        txt_EnrolledCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EnrolledCoursesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterLoginMainLayout = new javax.swing.GroupLayout(RegisterLoginMain);
        RegisterLoginMain.setLayout(RegisterLoginMainLayout);
        RegisterLoginMainLayout.setHorizontalGroup(
            RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                .addComponent(SideLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(RegisterName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                        .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(lbl_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                                        .addComponent(lbl_UniversityID)
                                        .addGap(226, 226, 226))
                                    .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                                            .addComponent(uniIcon)
                                            .addGap(37, 37, 37)
                                            .addComponent(txt_UniID, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(UniversityIDSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(UniversityIDSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbl_Password)
                                                .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                                                    .addComponent(passwordIcon)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                                                    .addComponent(FullNameIcon)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(UniversityIDSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegisterLoginMainLayout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(lbl_enrolledCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                                                    .addComponent(lbl_Email1)
                                                    .addGap(281, 281, 281))
                                                .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                                                        .addComponent(EmailIcon)
                                                        .addGap(40, 40, 40)
                                                        .addComponent(txt_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                                                    .addComponent(UniversityIDSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                                                .addComponent(EnrollIcon)
                                                .addGap(38, 38, 38)
                                                .addComponent(txt_EnrolledCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                        .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(lbl_validate, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(lbl_Already, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLoginMainLayout.createSequentialGroup()
                    .addContainerGap(406, Short.MAX_VALUE)
                    .addComponent(btn_register1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(169, 169, 169)))
        );
        RegisterLoginMainLayout.setVerticalGroup(
            RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                .addComponent(BackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegisterName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_validate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_UniversityID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uniIcon)
                    .addComponent(txt_UniID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UniversityIDSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FullNameIcon)
                    .addComponent(FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UniversityIDSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Email1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EmailIcon)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UniversityIDSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterLoginMainLayout.createSequentialGroup()
                        .addComponent(passwordIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UniversityIDSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_enrolledCourse))
                    .addComponent(txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnrollIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_EnrolledCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(lbl_Already)
                .addGap(34, 34, 34))
            .addGroup(RegisterLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLoginMainLayout.createSequentialGroup()
                    .addContainerGap(512, Short.MAX_VALUE)
                    .addComponent(btn_register1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(58, 58, 58)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterLoginMain, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterLoginMain, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(705, 596));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        //KioskMain kmr = new KioskMain();
        RegisterLogin rgf = new RegisterLogin();
        //kmr.setVisible(true);
        this.setVisible(false);
        //kmr.pack();
        //rgf.dispose();
        //new RegisterLogin().setVisible(false);

    }//GEN-LAST:event_jLabel2MouseClicked

    private void txt_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailActionPerformed

    private void lbl_AlreadyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AlreadyMouseClicked
        // TODO add your handling code here:
        
        Login lgf = new Login();
        lgf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_AlreadyMouseClicked

    private void txt_UniIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UniIDKeyPressed
        // TODO add your handling code here:
        
        char c =evt.getKeyChar();
        if(Character.isLetter(c)){
            lbl_validate.setText("*University ID cannot contain alphabets.");
            
        }else{
            txt_UniID.setEditable(true);
            lbl_validate.setText("");
        }
              
    }//GEN-LAST:event_txt_UniIDKeyPressed

    private void txt_EmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_EmailKeyPressed
        // TODO add your handling code here:
        
        boolean status=RegisterLogin.validateEmail(txt_Email.getText());
       if(status){
           lbl_validate.setText("*Given Email Address is Valid");
       }else{
           lbl_validate.setText("*Given Email Address is Not Valid");
          
       }
        
        
        
    }//GEN-LAST:event_txt_EmailKeyPressed

    private void txt_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PasswordKeyPressed
        // TODO add your handling code here:
        
        
        //char c =evt.getKeyChar(); //this char c is not used by KB
        String password=txt_Password.getText();
        int d =txt_Password.getText().length();
        
        boolean hasNum=false;
        boolean hasCap=false;
        boolean hasLow=false;
        char c;
        
        
        if(d!=7){
            lbl_validate.setText("*Given password is not valid.");
            
            
        }
        else{
            txt_Password.setEditable(true);
            lbl_validate.setText("*Given password is valid");
       
        }
        
        
        for(int i =0; i<d;i++)
        {
            c = password.charAt(i);
            if(Character.isDigit(c)){
                hasNum=true;
            }
            
            if(Character.isUpperCase(c)){
                hasCap=true;
            }
            
            if(Character.isLowerCase(c)){
                hasLow=true;
            }
            if(hasNum && hasCap && hasLow){
                lbl_validate.setText("*Given password is valid");
            }else{
            lbl_validate.setText("*Given password is not valid.");
            }
        }
       
        
               
       


        
    }//GEN-LAST:event_txt_PasswordKeyPressed

    private void FullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FullNameActionPerformed

    private void FullNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FullNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_FullNameKeyPressed

    private void btn_register1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_register1ActionPerformed
        // TODO add your handling code here:
        
         // Databse connectivity with our permanent OracleDatabase class such that it will be more agile(dyanmic)
        
       
       conn = OracleDatabase.ConnectDb();
       
       try{
           
           String sql = "insert into Student (UniversityID,StdName,StdEmail,Password,EnrolledCourse) values(?,?,?,?,?)";
           pst = (OraclePreparedStatement) conn.prepareStatement(sql);
           pst.setString(1,txt_UniID.getText());
           pst.setString(2,FullName.getText());
           pst.setString(3,txt_Email.getText());
           pst.setString(4,txt_Password.getText());
            String value = txt_EnrolledCourses.getSelectedItem().toString();
           pst.setString(5,value);
           
           rs =(OracleResultSet) pst.executeQuery();
           
           if (rs.next())
           {
               JOptionPane.showMessageDialog(null,"Registeration Successful.Now you will be redirected to login page");
               
               
                EnrollCourse();
                Login lgf = new Login();
                lgf.setVisible(true);
                this.dispose();
           }
           
           else
           {
               JOptionPane.showMessageDialog(null,"Registeration Unsuccessful.Please fill the registeration form carefully!!");
           }
          
       }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
       
    }//GEN-LAST:event_btn_register1ActionPerformed

    private void txt_EnrolledCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EnrolledCoursesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EnrolledCoursesActionPerformed
    
        
       
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackPanel;
    private javax.swing.JLabel EmailIcon;
    private javax.swing.JLabel EnrollIcon;
    private javax.swing.JTextField FullName;
    private javax.swing.JLabel FullNameIcon;
    private javax.swing.JLabel RegisterLoginIcon;
    private javax.swing.JPanel RegisterLoginMain;
    private javax.swing.JLabel RegisterName;
    private javax.swing.JPanel SideLogin;
    private javax.swing.JSeparator UniversityIDSeparator;
    private javax.swing.JSeparator UniversityIDSeparator1;
    private javax.swing.JSeparator UniversityIDSeparator2;
    private javax.swing.JSeparator UniversityIDSeparator4;
    private javax.swing.JButton btn_register1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbl_Already;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_Email1;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_UniversityID;
    private javax.swing.JLabel lbl_enrolledCourse;
    private javax.swing.JLabel lbl_validate;
    private javax.swing.JLabel passwordIcon;
    private javax.swing.JTextField txt_Email;
    public static javax.swing.JComboBox<String> txt_EnrolledCourses;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_UniID;
    private javax.swing.JLabel uniIcon;
    // End of variables declaration//GEN-END:variables
}
